# BEGIN_KITTY_THEME
include theme.conf
# END_KITTY_THEME
confirm_os_window_close 0
# startup_session ./startup.conf
# BEGIN_KITTY_THEME
include theme.conf
# END_KITTY_THEME
# startup_session ./startup.conf
