preload = /home/liz/Pictures/wallpapers/swayWallpaper.jpg
wallpaper = ,/home/liz/Pictures/wallpapers/swayWallpaper.jpg
wallpaper[]:path = /home/liz/Pictures/wallpapers/swayWallpaper.jpg
ipc = true
splash = false